# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      displayName: Build's displayname
      jobs:
          - job: 'j1'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here
                  
                  echo 'Hello world'
    - stage: Test
      displayName: Test's displayname
      jobs:
          - job: 'j2'
            steps:
            - task: Maven@3
              inputs:
                mavenPomFile: 'pom.xml'
                mavenOptions: '-Xmx3072m'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.8'
                jdkArchitectureOption: 'x64'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                goals: 'test'
                testRunTitle: 'j2'